# Generated by Django 4.2.5 on 2023-10-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0002_posts_subtite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtite',
            field=models.CharField(max_length=50),
        ),
    ]
