# Generated by Django 4.2.5 on 2023-10-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0003_alter_posts_subtite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
