# Generated by Django 4.2.5 on 2023-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0006_alter_books_title_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='user',
        ),
        migrations.AddField(
            model_name='opinion',
            name='sign',
            field=models.CharField(max_length=30, null='null'),
            preserve_default='null',
        ),
    ]
