# Generated by Django 4.2.5 on 2023-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0007_remove_opinion_user_opinion_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, null='null', unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='subtite',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
