# Generated by Django 4.2.5 on 2023-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0009_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='sign',
            field=models.CharField(max_length=30, null='null', unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='photos'),
        ),
    ]
