# Generated by Django 4.2.5 on 2023-10-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0010_alter_opinion_sign_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.CharField(max_length=100, null='null', unique=True),
        ),
    ]
