# Generated by Django 4.2.5 on 2023-10-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postit', '0011_alter_photo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.CharField(max_length=100, null='null'),
        ),
    ]
